name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t nikhil2523/chat-app-backend . 
      
      - name: Publish Docker Image
        run: docker push nikhil2523/chat-app-backend:latest 

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull nikhil2523/chat-app-backend:latest 

      - name: Stop and Remove Existing Container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 3000:3000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            -e MONGO_URI =${{secrets.MONGO_URI}} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
            -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
            -e PORT=${{ secrets.PORT }} \
            -e NODE_ENV=production \
            nikhil2523/chat-app-backend:latest
